// Generated by CoffeeScript 1.8.0
(function() {
  var ItemKey, keyList;

  keyList = {};

  ItemKey = (function() {
    function ItemKey(ref, selected, primary, secondary, grenade, other) {
      this.ref = ref;
      this.selected = selected != null ? selected : false;
      this.primary = primary != null ? primary : "";
      this.secondary = secondary != null ? secondary : "";
      this.grenade = grenade != null ? grenade : [];
      this.other = other != null ? other : [];
      if (selected) {
        ref.classList.add("savedKey");
      }
    }

    ItemKey.prototype.getValue = function() {
      if (this.ref.firstElementChild) {
        return this.ref.firstElementChild.innerHTML;
      } else {
        return this.ref.innerHTML;
      }
    };

    ItemKey.prototype.getString = function() {
      var g, grenadeS, o, otherS, _i, _j, _len, _len1, _ref, _ref1;
      grenadeS = "";
      otherS = "";
      if (this.grenade.length > 0) {
        _ref = this.grenade;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          g = _ref[_i];
          grenadeS += g + " ";
        }
      }
      if (this.other.length > 0) {
        _ref1 = this.other;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          o = _ref1[_j];
          otherS += o + " ";
        }
      }
      return "bind " + "\"" + this.getValue() + "\" \"" + this.primary + this.secondary + grenadeS + otherS + "\"&#10;";
    };

    ItemKey.prototype.select = function() {
      this.selected = true;
      return this.ref.classList.add("savedKey");
    };

    ItemKey.prototype.deSelect = function() {
      this.selected = false;
      return this.ref.classList.remove("savedKey");
    };

    return ItemKey;

  })();

  window.itemKey = ItemKey;

  window.keyList = keyList;

}).call(this);
